version: "2.4"
services:

  coaguscan:
    image: clotspot/coaguscan
    privileged: true
    # Accept the EULA required to run imx8 vivante graphic drivers
    environment:
     - ACCEPT_FSL_EULA=1
    ports:
      - "55555:55555"
    device_cgroup_rules:
      # ... for /dev/dri devices
      - 'c 226:* rmw'
      - 'c 199:* rmw'
      # ... for USB devices
      - 'b 8:* rmw'
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /media
        target: /media
        bind:
          propagation: shared
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus
      - data:/opt/data

volumes:
  data:
